name: prenotami parsed

on:
  schedule:
    - cron: "*/6 * * * *"

env:
  LOGIN: ${{ secrets.LOGIN }}
  PASSWORD: ${{ secrets.PASSWORD }}
  USER_NAME: ${{ secrets.USER_NAME }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run App
        run: python main.py